//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;

using LinqToDB;
using LinqToDB.Configuration;
using LinqToDB.Mapping;

namespace QuyLe.Core.Domain.Editor
{
	/// <summary>
	/// Database       : quyleeditor
	/// Data Source    : lobstersanco.xyz. \MSSQLSERVER2012, 1433
	/// Server Version : 11.00.6020
	/// </summary>
	public partial class EditorDataConnection : LinqToDB.Data.DataConnection
	{
		public ITable<Draft>             Drafts              { get { return this.GetTable<Draft>(); } }
		public ITable<DraftDetail>       DraftDetails        { get { return this.GetTable<DraftDetail>(); } }
		public ITable<Paragraph>         Paragraphs          { get { return this.GetTable<Paragraph>(); } }
		public ITable<ParagraphCategory> ParagraphCategories { get { return this.GetTable<ParagraphCategory>(); } }
		public ITable<Topic>             Topics              { get { return this.GetTable<Topic>(); } }

		public EditorDataConnection()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public EditorDataConnection(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public EditorDataConnection(LinqToDbConnectionOptions options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public EditorDataConnection(LinqToDbConnectionOptions<EditorDataConnection> options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}

	[Table(Schema="rdy", Name="Draft")]
	public partial class Draft
	{
		[PrimaryKey, NotNull    ] public string   Id           { get; set; } // varchar(36)
		[Column,     NotNull    ] public string   Code         { get; set; } // varchar(50)
		[Column,     NotNull    ] public string   Name         { get; set; } // varchar(150)
		[Column,        Nullable] public string   Title        { get; set; } // nvarchar(255)
		[Column,        Nullable] public string   Description  { get; set; } // nvarchar(255)
		[Column,        Nullable] public string   Reference    { get; set; } // nvarchar(255)
		[Column,        Nullable] public string   TopicId      { get; set; } // varchar(36)
		[Column,        Nullable] public string   CreatedBy    { get; set; } // varchar(36)
		[Column,     NotNull    ] public DateTime CreatedDate  { get; set; } // datetime
		[Column,        Nullable] public string   ModifiedBy   { get; set; } // varchar(36)
		[Column,     NotNull    ] public DateTime ModifiedDate { get; set; } // datetime

		#region Associations

		/// <summary>
		/// FK__Draft__TopicId__1A14E395
		/// </summary>
		[Association(ThisKey="TopicId", OtherKey="Id", CanBeNull=true, Relationship=LinqToDB.Mapping.Relationship.ManyToOne, KeyName="FK__Draft__TopicId__1A14E395", BackReferenceName="FkDraftTopicId1A14E395BackReferences")]
		public Topic DraftTopicId1A14E395 { get; set; }

		/// <summary>
		/// FK__DraftDeta__Draft__1920BF5C_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="DraftId", CanBeNull=true, Relationship=LinqToDB.Mapping.Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<DraftDetail> FkDraftDetaDraft1920BF5CBackReferences { get; set; }

		#endregion
	}

	[Table(Schema="rdy", Name="DraftDetail")]
	public partial class DraftDetail
	{
		[PrimaryKey, NotNull] public string Id          { get; set; } // varchar(36)
		[Column,     NotNull] public string ParagraphId { get; set; } // varchar(36)
		[Column,     NotNull] public int    Order       { get; set; } // int
		[Column,     NotNull] public string DraftId     { get; set; } // varchar(36)

		#region Associations

		/// <summary>
		/// FK__DraftDeta__Draft__1920BF5C
		/// </summary>
		[Association(ThisKey="DraftId", OtherKey="Id", CanBeNull=false, Relationship=LinqToDB.Mapping.Relationship.ManyToOne, KeyName="FK__DraftDeta__Draft__1920BF5C", BackReferenceName="FkDraftDetaDraft1920BF5CBackReferences")]
		public Draft DraftDetaDraft1920BF5C { get; set; }

		/// <summary>
		/// FK__DraftDeta__Parag__1B0907CE
		/// </summary>
		[Association(ThisKey="ParagraphId", OtherKey="Id", CanBeNull=false, Relationship=LinqToDB.Mapping.Relationship.ManyToOne, KeyName="FK__DraftDeta__Parag__1B0907CE", BackReferenceName="FkDraftDetaParag1B0907CEBackReferences")]
		public Paragraph DraftDetaParag1B0907CE { get; set; }

		#endregion
	}

	[Table(Schema="rdy", Name="Paragraph")]
	public partial class Paragraph
	{
		[PrimaryKey, NotNull    ] public string Id          { get; set; } // varchar(36)
		[Column,     NotNull    ] public string Code        { get; set; } // varchar(50)
		[Column,     NotNull    ] public string Name        { get; set; } // varchar(150)
		[Column,        Nullable] public string Description { get; set; } // nvarchar(255)
		[Column,        Nullable] public string Title       { get; set; } // nvarchar(255)
		[Column,        Nullable] public string CategoryId  { get; set; } // varchar(36)
		[Column,     NotNull    ] public bool   InUse       { get; set; } // bit

		#region Associations

		/// <summary>
		/// FK__DraftDeta__Parag__1B0907CE_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="ParagraphId", CanBeNull=true, Relationship=LinqToDB.Mapping.Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<DraftDetail> FkDraftDetaParag1B0907CEBackReferences { get; set; }

		/// <summary>
		/// FK__Paragraph__Categ__1BFD2C07
		/// </summary>
		[Association(ThisKey="CategoryId", OtherKey="Id", CanBeNull=true, Relationship=LinqToDB.Mapping.Relationship.ManyToOne, KeyName="FK__Paragraph__Categ__1BFD2C07", BackReferenceName="FkParagraphCateg1BFD2C07BackReferences")]
		public ParagraphCategory ParagraphCateg1BFD2C07 { get; set; }

		#endregion
	}

	[Table(Schema="rdy", Name="ParagraphCategory")]
	public partial class ParagraphCategory
	{
		[PrimaryKey, NotNull    ] public string Id          { get; set; } // varchar(36)
		[Column,     NotNull    ] public string Code        { get; set; } // varchar(50)
		[Column,     NotNull    ] public string Name        { get; set; } // varchar(150)
		[Column,        Nullable] public string ParentId    { get; set; } // varchar(36)
		[Column,        Nullable] public string Path        { get; set; } // nvarchar(255)
		[Column,        Nullable] public string Description { get; set; } // nvarchar(255)
		[Column,     NotNull    ] public bool   InUse       { get; set; } // bit

		#region Associations

		/// <summary>
		/// FK__Paragraph__Categ__1BFD2C07_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="CategoryId", CanBeNull=true, Relationship=LinqToDB.Mapping.Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<Paragraph> FkParagraphCateg1BFD2C07BackReferences { get; set; }

		#endregion
	}

	[Table(Schema="rdy", Name="Topic")]
	public partial class Topic
	{
		[PrimaryKey, NotNull    ] public string Id       { get; set; } // varchar(36)
		[Column,     NotNull    ] public string Code     { get; set; } // varchar(50)
		[Column,     NotNull    ] public string Name     { get; set; } // varchar(150)
		[Column,        Nullable] public string ParentId { get; set; } // varchar(36)
		[Column,        Nullable] public string Path     { get; set; } // nvarchar(255)
		[Column,     NotNull    ] public bool   InUse    { get; set; } // bit

		#region Associations

		/// <summary>
		/// FK__Draft__TopicId__1A14E395_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="TopicId", CanBeNull=true, Relationship=LinqToDB.Mapping.Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<Draft> FkDraftTopicId1A14E395BackReferences { get; set; }

		#endregion
	}

	public static partial class TableExtensions
	{
		public static Draft Find(this ITable<Draft> table, string Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static DraftDetail Find(this ITable<DraftDetail> table, string Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static Paragraph Find(this ITable<Paragraph> table, string Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static ParagraphCategory Find(this ITable<ParagraphCategory> table, string Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static Topic Find(this ITable<Topic> table, string Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}
	}
}

#pragma warning restore 1591
